In [1]:
#Importing the excel file
import pandas as pd

df = pd.read_excel('TradeStat-Eidb-Import-Commodity-wise.xlsx', dtype=str)

df.head()

,TradeStat->Eidb->Import->Commodity-wise,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Report Generated on: 11/10/2026 - Values in US...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S.No.,HSCode,Commodity,2024 - 2025,%Share,2025 - 2026,%Share,%Growth
2,1,0101,"LIVE HORSES, ASSES, MULES AND HINNIES",12.11,0.0017,7.35,0.0009,-39.33
3,2,0102,LIVE BOVINE ANIMALS,0.03,0,1.3,0.0002,3937.28
4,3,0103,LIVE SWINE,0.24,0,0.4,0.0001,67.6

In [2]:
#Deleting the first row
df = df.iloc[1:]
df.head()

,TradeStat->Eidb->Import->Commodity-wise,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
1,S.No.,HSCode,Commodity,2024 - 2025,%Share,2025 - 2026,%Share,%Growth
2,1,0101,"LIVE HORSES, ASSES, MULES AND HINNIES",12.11,0.0017,7.35,0.0009,-39.33
3,2,0102,LIVE BOVINE ANIMALS,0.03,0,1.3,0.0002,3937.28
4,3,0103,LIVE SWINE,0.24,0,0.4,0.0001,67.6
5,4,0104,LIVE SHEEP AND GOATS,0.07,0,2.65,0.0003,3592.3

In [3]:
#Moving first row to header. Fixing the attributes
df.columns = df.iloc[0]
df = df[1:]
df.reset_index(drop=True, inplace=True)

In [4]:
df.head()

1,S.No.,HSCode,Commodity,2024 - 2025,%Share,2025 - 2026,%Share,%Growth
0,1,0101,"LIVE HORSES, ASSES, MULES AND HINNIES",12.11,0.0017,7.35,0.0009,-39.33
1,2,0102,LIVE BOVINE ANIMALS,0.03,0,1.3,0.0002,3937.28
2,3,0103,LIVE SWINE,0.24,0,0.4,0.0001,67.6
3,4,0104,LIVE SHEEP AND GOATS,0.07,0,2.65,0.0003,3592.3
4,5,0105,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",3.37,0.0005,4.15,0.0005,23.08

In [5]:
#Removing unwanted colums 2024-2025, %Share, %Growth
df = df.drop(columns=["2024 - 2025", "%Share", "%Growth"])
df.head()

1 S.No. HSCode                                          Commodity 2025 - 2026
0     1   0101              LIVE HORSES, ASSES, MULES AND HINNIES        7.35
1     2   0102                                LIVE BOVINE ANIMALS         1.3
2     3   0103                                         LIVE SWINE         0.4
3     4   0104                               LIVE SHEEP AND GOATS        2.65
4     5   0105  LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...        4.15

In [6]:
#Rename the columns
df = df.rename(columns={'S.No.': 'commodity_key', 'HSCode': 'hs4_code', 'Commodity': 'description', '2025 - 2026': '2025_2026'})
df.head()

1,commodity_key,hs4_code,description,2025_2026
0,1,0101,"LIVE HORSES, ASSES, MULES AND HINNIES",7.35
1,2,0102,LIVE BOVINE ANIMALS,1.3
2,3,0103,LIVE SWINE,0.4
3,4,0104,LIVE SHEEP AND GOATS,2.65
4,5,0105,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",4.15

In [7]:
#Creating a new columns of just first two numbers in hs4_code
df["hs2_code"] = df["hs4_code"].str[:2]
df.head()

1,commodity_key,hs4_code,description,2025_2026,hs2_code
0,1,0101,"LIVE HORSES, ASSES, MULES AND HINNIES",7.35,01
1,2,0102,LIVE BOVINE ANIMALS,1.3,01
2,3,0103,LIVE SWINE,0.4,01
3,4,0104,LIVE SHEEP AND GOATS,2.65,01
4,5,0105,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",4.15,01

In [8]:
df_hs2 = pd.read_excel('TradeStat-Eidb-Import-Commodity-wise-hs2.xlsx', dtype=str)
df_hs2.head()

,TradeStat->Eidb->Import->Commodity-wise,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Report Generated on: 11/10/2026 - Values in US...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S.No.,HSCode,Commodity,2024 - 2025,%Share,2025 - 2026,%Share,%Growth
2,1,01,LIVE ANIMALS.,26.24,0.0036,24.52,0.0032,-6.52
3,2,02,MEAT AND EDIBLE MEAT OFFAL.,7.64,0.0011,13.53,0.0017,76.98
4,3,03,"FISH AND CRUSTACEANS, MOLLUSCS AND OTHER AQUAT...",234.09,0.0325,289.58,0.0373,23.71

In [9]:
#Deleting the first row
df_hs2 = df_hs2.iloc[1:]
df_hs2.head()

,TradeStat->Eidb->Import->Commodity-wise,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
1,S.No.,HSCode,Commodity,2024 - 2025,%Share,2025 - 2026,%Share,%Growth
2,1,01,LIVE ANIMALS.,26.24,0.0036,24.52,0.0032,-6.52
3,2,02,MEAT AND EDIBLE MEAT OFFAL.,7.64,0.0011,13.53,0.0017,76.98
4,3,03,"FISH AND CRUSTACEANS, MOLLUSCS AND OTHER AQUAT...",234.09,0.0325,289.58,0.0373,23.71
5,4,04,DAIRY PRODUCE; BIRDS' EGGS; NATURAL HONEY; EDI...,45.68,0.0063,79.85,0.0103,74.82

In [10]:
#Moving first row to header. Fixing the attributes
df_hs2.columns = df_hs2.iloc[0]
df_hs2 = df_hs2[1:]
df_hs2.reset_index(drop=True, inplace=True)
df_hs2.head()

1,S.No.,HSCode,Commodity,2024 - 2025,%Share,2025 - 2026,%Share,%Growth
0,1,01,LIVE ANIMALS.,26.24,0.0036,24.52,0.0032,-6.52
1,2,02,MEAT AND EDIBLE MEAT OFFAL.,7.64,0.0011,13.53,0.0017,76.98
2,3,03,"FISH AND CRUSTACEANS, MOLLUSCS AND OTHER AQUAT...",234.09,0.0325,289.58,0.0373,23.71
3,4,04,DAIRY PRODUCE; BIRDS' EGGS; NATURAL HONEY; EDI...,45.68,0.0063,79.85,0.0103,74.82
4,5,05,"PRODUCTS OF ANIMAL ORIGIN, NOT ELSEWHERE SPECI...",44.51,0.0062,54.63,0.007,22.72

In [11]:
#Removing unwanted colums 2024-2025, %Share, %Growth
df_hs2 = df_hs2.drop(columns=["2024 - 2025", "%Share", "%Growth", "2025 - 2026"])
df_hs2.head()

1 S.No. HSCode                                          Commodity
0     1     01                                      LIVE ANIMALS.
1     2     02                        MEAT AND EDIBLE MEAT OFFAL.
2     3     03  FISH AND CRUSTACEANS, MOLLUSCS AND OTHER AQUAT...
3     4     04  DAIRY PRODUCE; BIRDS' EGGS; NATURAL HONEY; EDI...
4     5     05  PRODUCTS OF ANIMAL ORIGIN, NOT ELSEWHERE SPECI...

In [12]:
#Rename the columns
df_hs2 = df_hs2.rename(columns={'S.No.': 'chapter_key', 'HSCode': 'hs2_code', 'Commodity': 'commodity'})
df_hs2.head()

1 chapter_key hs2_code                                          commodity
0           1       01                                      LIVE ANIMALS.
1           2       02                        MEAT AND EDIBLE MEAT OFFAL.
2           3       03  FISH AND CRUSTACEANS, MOLLUSCS AND OTHER AQUAT...
3           4       04  DAIRY PRODUCE; BIRDS' EGGS; NATURAL HONEY; EDI...
4           5       05  PRODUCTS OF ANIMAL ORIGIN, NOT ELSEWHERE SPECI...

In [13]:
merged_df = pd.merge(df,df_hs2, on="hs2_code")
merged_df.head()

1,commodity_key,hs4_code,description,2025_2026,hs2_code,chapter_key,commodity
0,1,0101,"LIVE HORSES, ASSES, MULES AND HINNIES",7.35,01,1,LIVE ANIMALS.
1,2,0102,LIVE BOVINE ANIMALS,1.3,01,1,LIVE ANIMALS.
2,3,0103,LIVE SWINE,0.4,01,1,LIVE ANIMALS.
3,4,0104,LIVE SHEEP AND GOATS,2.65,01,1,LIVE ANIMALS.
4,5,0105,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",4.15,01,1,LIVE ANIMALS.

In [14]:
#Removing unwanted colums
merged_df = merged_df.drop(columns=["chapter_key"])
merged_df.head()

1,commodity_key,hs4_code,description,2025_2026,hs2_code,commodity
0,1,0101,"LIVE HORSES, ASSES, MULES AND HINNIES",7.35,01,LIVE ANIMALS.
1,2,0102,LIVE BOVINE ANIMALS,1.3,01,LIVE ANIMALS.
2,3,0103,LIVE SWINE,0.4,01,LIVE ANIMALS.
3,4,0104,LIVE SHEEP AND GOATS,2.65,01,LIVE ANIMALS.
4,5,0105,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",4.15,01,LIVE ANIMALS.

In [15]:
#Rearranging the columns
merged_df = merged_df[["commodity_key", "hs2_code", "hs4_code", "commodity", "description", "2025_2026"]]
merged_df.head()

1,commodity_key,hs2_code,hs4_code,commodity,description,2025_2026
0,1,01,0101,LIVE ANIMALS.,"LIVE HORSES, ASSES, MULES AND HINNIES",7.35
1,2,01,0102,LIVE ANIMALS.,LIVE BOVINE ANIMALS,1.3
2,3,01,0103,LIVE ANIMALS.,LIVE SWINE,0.4
3,4,01,0104,LIVE ANIMALS.,LIVE SHEEP AND GOATS,2.65
4,5,01,0105,LIVE ANIMALS.,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",4.15

In [16]:
#Rename the columns
merged_df = merged_df.rename(columns={'2025_2026': '2025_2026_import_sales_usd'})
merged_df.head()

1,commodity_key,hs2_code,hs4_code,commodity,description,2025_2026_import_sales_usd
0,1,01,0101,LIVE ANIMALS.,"LIVE HORSES, ASSES, MULES AND HINNIES",7.35
1,2,01,0102,LIVE ANIMALS.,LIVE BOVINE ANIMALS,1.3
2,3,01,0103,LIVE ANIMALS.,LIVE SWINE,0.4
3,4,01,0104,LIVE ANIMALS.,LIVE SHEEP AND GOATS,2.65
4,5,01,0105,LIVE ANIMALS.,"LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPE...",4.15

In [17]:
merged_df['2025_2026_import_sales_usd'] = pd.to_numeric(merged_df['2025_2026_import_sales_usd'])

In [18]:
merged_df.to_excel('dim_commodity.xlsx', index=False)